// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"github.com/oodle-ai/opentelemetry-collector/component"
)

var (
	Type = component.MustNewType("debug")
)

const (
	TracesStability  = component.StabilityLevelDevelopment
	MetricsStability = component.StabilityLevelDevelopment
	LogsStability    = component.StabilityLevelDevelopment
)
