// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"github.com/oodle-ai/opentelemetry-collector/component"
)

var (
	Type = component.MustNewType("sample")
)

const (
	LogsStability    = component.StabilityLevelDevelopment
	TracesStability  = component.StabilityLevelBeta
	MetricsStability = component.StabilityLevelStable
)
