// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"github.com/oodle-ai/opentelemetry-collector/component"
)

var (
	Type = component.MustNewType("logging")
)

const (
	TracesStability  = component.StabilityLevelDeprecated
	MetricsStability = component.StabilityLevelDeprecated
	LogsStability    = component.StabilityLevelDeprecated
)
