// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

package internal // import "github.com/oodle-ai/opentelemetry-collector/pdata/internal/cmd/pdatagen/internal"

import (
	"bytes"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

const header = `// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "pdata/internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".`

// AllPackages is a list of all packages that needs to be generated.
var AllPackages = []*Package{
	pcommon,
	plog,
	plogotlp,
	pmetric,
	pmetricotlp,
	ptrace,
	ptraceotlp,
	pprofile,
	pprofileotlp,
}

// Package is a struct used to generate files.
type Package struct {
	name        string
	path        string
	imports     []string
	testImports []string
	// Can be any of sliceOfPtrs, sliceOfValues, messageValueStruct, or messagePtrStruct
	structs []baseStruct
}

const newLine = "\n"

var importAliasRe = regexp.MustCompile(
	`^\s*(\w+)\s+"[^"]*"$`,
)

func filterImports(
	allImports []string,
	code string,
) []string {
	var result []string
	for _, imp := range allImports {
		if imp == "" {
			result = append(result, imp)
			continue
		}
		m := importAliasRe.FindStringSubmatch(imp)
		if m != nil {
			alias := m[1]
			if strings.Contains(code, alias+".") {
				result = append(result, imp)
			}
			continue
		}
		pkg := imp
		pkg = strings.Trim(pkg, `" `)
		if i := strings.LastIndex(pkg, "/"); i >= 0 {
			pkg = pkg[i+1:]
		}
		if strings.Contains(code, pkg+".") ||
			strings.Contains(code, `"`+strings.Trim(imp, `" `)+`"`) {
			result = append(result, imp)
		}
	}
	// Remove trailing empty separators
	for len(result) > 0 && result[len(result)-1] == "" {
		result = result[:len(result)-1]
	}
	// Remove leading empty separators
	for len(result) > 0 && result[0] == "" {
		result = result[1:]
	}
	// Remove consecutive empty separators
	var cleaned []string
	for i, imp := range result {
		if imp == "" && i > 0 && result[i-1] == "" {
			continue
		}
		cleaned = append(cleaned, imp)
	}
	return cleaned
}

func writeImports(sb *bytes.Buffer, imports []string) {
	sb.WriteString("import (" + newLine)
	for _, imp := range imports {
		if imp != "" {
			sb.WriteString("\t" + imp + newLine)
		} else {
			sb.WriteString(newLine)
		}
	}
	sb.WriteString(")")
}

// GenerateFiles generates files with the configured data structures for this Package.
func (p *Package) GenerateFiles() error {
	for _, s := range p.structs {
		var codeBuf bytes.Buffer
		s.generateStruct(&codeBuf)
		code := codeBuf.String()

		var sb bytes.Buffer
		generateHeader(&sb, p.name)
		writeImports(&sb, filterImports(p.imports, code))
		sb.WriteString(newLine + newLine)
		sb.WriteString(code)
		sb.WriteString(newLine)

		path := filepath.Join(
			"pdata", p.path,
			"generated_"+strings.ToLower(s.getName())+".go",
		)
		//nolint:gosec
		if err := os.WriteFile(path, sb.Bytes(), 0644); err != nil {
			return err
		}
	}
	return nil
}

// GenerateTestFiles generates files with tests for the configured data structures for this Package.
func (p *Package) GenerateTestFiles() error {
	for _, s := range p.structs {
		var codeBuf bytes.Buffer
		s.generateTests(&codeBuf)
		if !usedByOtherDataTypes(p.name) {
			codeBuf.WriteString(newLine + newLine)
			s.generateTestValueHelpers(&codeBuf)
		}
		code := codeBuf.String()

		var sb bytes.Buffer
		generateHeader(&sb, p.name)
		writeImports(
			&sb, filterImports(p.testImports, code),
		)
		sb.WriteString(newLine + newLine)
		sb.WriteString(code)

		path := filepath.Join(
			"pdata", p.path,
			"generated_"+strings.ToLower(s.getName())+"_test.go",
		)
		//nolint:gosec
		if err := os.WriteFile(path, sb.Bytes(), 0644); err != nil {
			return err
		}
	}
	return nil
}

// GenerateInternalFiles generates files with internal pdata structures for this Package.
func (p *Package) GenerateInternalFiles() error {
	if !usedByOtherDataTypes(p.name) {
		return nil
	}

	internalSelf := `"github.com/oodle-ai/opentelemetry-collector/pdata/internal"`
	var internalImports []string
	for _, imp := range p.imports {
		if imp != internalSelf {
			internalImports = append(internalImports, imp)
		}
	}

	for _, s := range p.structs {
		var codeBuf bytes.Buffer
		s.generateInternal(&codeBuf)
		codeBuf.WriteString(newLine + newLine)
		s.generateTestValueHelpers(&codeBuf)
		code := codeBuf.String()

		var sb bytes.Buffer
		generateHeader(&sb, "internal")
		writeImports(
			&sb,
			filterImports(internalImports, code),
		)
		sb.WriteString(newLine)
		sb.WriteString(code)
		sb.WriteString(newLine)

		path := filepath.Join(
			"pdata", "internal",
			"generated_wrapper_"+strings.ToLower(s.getName())+".go",
		)
		//nolint:gosec
		if err := os.WriteFile(path, sb.Bytes(), 0644); err != nil {
			return err
		}
	}
	return nil
}

func generateHeader(sb *bytes.Buffer, packageName string) {
	sb.WriteString(header)
	sb.WriteString(newLine + newLine)
	sb.WriteString("package " + packageName)
	sb.WriteString(newLine + newLine)
}

// usedByOtherDataTypes defines if the package is used by other data types and orig fields of the package's structs
// need to be accessible from other pdata packages.
func usedByOtherDataTypes(packageName string) bool {
	return packageName == "pcommon"
}
