dist:
  module: github.com/oodle-ai/opentelemetry-collector/cmd/otelcorecol
  name: otelcorecol
  description: Local OpenTelemetry Collector binary, testing only.
  version: 0.101.0-dev
  otelcol_version: 0.101.0

receivers:
  - gomod: github.com/oodle-ai/opentelemetry-collector/receiver/nopreceiver v0.101.0
  - gomod: github.com/oodle-ai/opentelemetry-collector/receiver/otlpreceiver v0.101.0
exporters:
  - gomod: github.com/oodle-ai/opentelemetry-collector/exporter/debugexporter v0.101.0
  - gomod: github.com/oodle-ai/opentelemetry-collector/exporter/loggingexporter v0.101.0
  - gomod: github.com/oodle-ai/opentelemetry-collector/exporter/nopexporter v0.101.0
  - gomod: github.com/oodle-ai/opentelemetry-collector/exporter/otlpexporter v0.101.0
  - gomod: github.com/oodle-ai/opentelemetry-collector/exporter/otlphttpexporter v0.101.0
extensions:
  - gomod: github.com/oodle-ai/opentelemetry-collector/extension/ballastextension v0.101.0
  - gomod: github.com/oodle-ai/opentelemetry-collector/extension/memorylimiterextension v0.101.0
  - gomod: github.com/oodle-ai/opentelemetry-collector/extension/zpagesextension v0.101.0
processors:
  - gomod: github.com/oodle-ai/opentelemetry-collector/processor/batchprocessor v0.101.0
  - gomod: github.com/oodle-ai/opentelemetry-collector/processor/memorylimiterprocessor v0.101.0
connectors:
  - gomod: github.com/oodle-ai/opentelemetry-collector/connector/forwardconnector v0.101.0

providers:
  - gomod: github.com/oodle-ai/opentelemetry-collector/confmap/provider/envprovider v0.101.0
  - gomod: github.com/oodle-ai/opentelemetry-collector/confmap/provider/fileprovider v0.101.0
  - gomod: github.com/oodle-ai/opentelemetry-collector/confmap/provider/httpprovider v0.101.0
  - gomod: github.com/oodle-ai/opentelemetry-collector/confmap/provider/httpsprovider v0.101.0
  - gomod: github.com/oodle-ai/opentelemetry-collector/confmap/provider/yamlprovider v0.101.0

