// Code generated by "github.com/oodle-ai/opentelemetry-collector/cmd/builder". DO NOT EDIT.

// Program otelcorecol is an OpenTelemetry Collector binary.
package main

import (
	"log"

	"github.com/oodle-ai/opentelemetry-collector/component"
	"github.com/oodle-ai/opentelemetry-collector/confmap"
	"github.com/oodle-ai/opentelemetry-collector/confmap/converter/expandconverter"
	envprovider "github.com/oodle-ai/opentelemetry-collector/confmap/provider/envprovider"
	fileprovider "github.com/oodle-ai/opentelemetry-collector/confmap/provider/fileprovider"
	httpprovider "github.com/oodle-ai/opentelemetry-collector/confmap/provider/httpprovider"
	httpsprovider "github.com/oodle-ai/opentelemetry-collector/confmap/provider/httpsprovider"
	yamlprovider "github.com/oodle-ai/opentelemetry-collector/confmap/provider/yamlprovider"
	"github.com/oodle-ai/opentelemetry-collector/otelcol"
)

func main() {
	info := component.BuildInfo{
		Command:     "otelcorecol",
		Description: "Local OpenTelemetry Collector binary, testing only.",
		Version:     "0.101.0-dev",
	}

	set := otelcol.CollectorSettings{
		BuildInfo: info,
		Factories: components,
		ConfigProviderSettings: otelcol.ConfigProviderSettings{
			ResolverSettings: confmap.ResolverSettings{
				ProviderFactories: []confmap.ProviderFactory{
					envprovider.NewFactory(),
					fileprovider.NewFactory(),
					httpprovider.NewFactory(),
					httpsprovider.NewFactory(),
					yamlprovider.NewFactory(),
				},
				ConverterFactories: []confmap.ConverterFactory{
					expandconverter.NewFactory(),
				},
			},
		},
	}

	if err := run(set); err != nil {
		log.Fatal(err)
	}
}

func runInteractive(params otelcol.CollectorSettings) error {
	cmd := otelcol.NewCommand(params)
	if err := cmd.Execute(); err != nil {
		log.Fatalf("collector server run finished with error: %v", err)
	}

	return nil
}
