// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"github.com/oodle-ai/opentelemetry-collector/component"
)

var (
	Type = component.MustNewType("zpages")
)

const (
	ExtensionStability = component.StabilityLevelBeta
)
